In [1]:
# Import Libraries

import pandas as pd
import numpy as np

In [2]:
# Upload Dataset

from google.colab import files
uploaded = files.upload()

Saving processed-data.csv to processed-data.csv

In [3]:
# Load Dataset

df = pd.read_csv("processed-data.csv")
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,...,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,...,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,...,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,...,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,...,3,4,1,6,3,3,2,2,2,2

In [4]:
# Convert Target Variable

df["Attrition"] = df["Attrition"].map({"Yes":1, "No":0})
df["Attrition"].value_counts()

Attrition
0    1233
1     237
Name: count, dtype: int64

In [5]:
# Income per Experience Year

df["IncomePerYear"] = df["MonthlyIncome"] / (df["TotalWorkingYears"] + 1)

In [6]:
# Promotion Gap

df["PromotionGap"] = df["YearsAtCompany"] - df["YearsSinceLastPromotion"]

In [7]:
# Company Experience Ratio

df["CompanyExperienceRatio"] = df["YearsAtCompany"] / (df["TotalWorkingYears"] + 1)

In [8]:
# Manager Stability

df["ManagerStability"] = df["YearsWithCurrManager"] / (df["YearsAtCompany"] + 1)

In [9]:
# Workload Indicator

df["WorkloadScore"] = df["JobInvolvement"] + df["WorkLifeBalance"]

In [10]:
# Salary Growth Indicator

df["SalaryGrowth"] = df["PercentSalaryHike"] / 100

In [11]:
# Identify Categorical Columns

categorical_cols = df.select_dtypes(include=["object"]).columns
categorical_cols

Index(['BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole',
       'MaritalStatus', 'OverTime'],
      dtype='object')

In [22]:
# Encode Categorical Variables

categorical_cols = df.select_dtypes(include=["object"]).columns
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

In [23]:
# Feature Scaling

from sklearn.preprocessing import StandardScaler
X = df.drop("Attrition", axis=1)
y = df["Attrition"]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

df_scaled = pd.DataFrame(X_scaled, columns=X.columns, index=df.index)
df_scaled["Attrition"] = y

df = df_scaled

In [24]:
# Check Final Feature Dataset

df.head()

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes,Attrition
0,0.446350,0.742527,-1.010909,-0.891688,-0.660531,1.383138,0.379672,-0.057788,1.153254,-0.108350,...,-0.273059,-0.330808,-0.239904,-0.497873,1.873287,-0.244625,-0.918921,1.458650,1.591746,1
1,1.322365,-1.297775,-0.147150,-1.868426,0.254625,-0.240677,-1.026167,-0.057788,-0.660853,-0.291719,...,-0.273059,-0.330808,-0.239904,2.008543,-0.533821,-0.244625,1.088232,-0.685565,-0.628241,0
2,0.008343,1.414363,-0.887515,-0.891688,1.169781,1.284725,-1.026167,-0.961486,0.246200,-0.937654,...,-0.273059,-0.330808,-0.239904,-0.497873,-0.533821,-0.244625,-0.918921,1.458650,1.591746,1
3,-0.429664,1.461466,-0.764121,1.061787,1.169781,-0.486709,0.379672,-0.961486,0.246200,-0.763634,...,-0.273059,-0.330808,-0.239904,2.008543,-0.533821,-0.244625,1.088232,-0.685565,1.591746,0
4,-1.086676,-0.524295,-0.887515,-1.868426,-1.575686,-1.274014,0.379672,-0.961486,-0.660853,-0.644858,...,-0.273059,-0.330808,-0.239904,-0.497873,-0.533821,-0.244625,1.088232,-0.685565,-0.628241,0

In [25]:
df.shape

(1470, 51)

In [26]:
# Save Feature-Engineered Dataset

df.to_csv("feature-engineered-data.csv", index=False)

In [27]:
# Download Dataset

files.download("feature-engineered-data.csv")